USE coworking_space;

-- Q4: What is the total revenue generated by each membership plan?
SELECT
    MembershipPlans.plan_name,
    COUNT(Payments.payment_id) AS total_sales,
    SUM(Payments.amount) AS total_revenue
FROM MembershipPlans
JOIN Payments ON MembershipPlans.plan_id = Payments.plan_id
GROUP BY MembershipPlans.plan_name
ORDER BY total_revenue DESC;

-- Q5: Which are the top 5 most booked spaces?
SELECT
    Spaces.space_name,
    Spaces.space_type,
    COUNT(Bookings.booking_id) AS booking_count
FROM Spaces
JOIN Bookings ON Spaces.space_id = Bookings.space_id
WHERE Bookings.is_cancelled = 0
GROUP BY Spaces.space_id, Spaces.space_name, Spaces.space_type
ORDER BY booking_count DESC
LIMIT 5;

-- Q6: Who are the top 10 members by total money spent?
SELECT
    Members.first_name,
    Members.last_name,
    SUM(Payments.amount) AS total_spent
FROM Members
JOIN Payments ON Members.member_id = Payments.member_id
GROUP BY Members.member_id, Members.first_name, Members.last_name
ORDER BY total_spent DESC
LIMIT 10;

-- Q7: How many hours of usage has each workspace type provided?
SELECT
    Spaces.space_type,
    SUM(TIMESTAMPDIFF(HOUR, Bookings.start_time, Bookings.end_time)) AS total_hours_booked
FROM Spaces
JOIN Bookings ON Spaces.space_id = Bookings.space_id
WHERE Bookings.is_cancelled = 0
GROUP BY Spaces.space_type
ORDER BY total_hours_booked DESC;

-- Q8: What are the busiest days of the week?
SELECT
    DAYNAME(Bookings.booking_date) AS day_of_week,
    COUNT(Bookings.booking_id) AS total_bookings
FROM Bookings
WHERE Bookings.is_cancelled = 0
GROUP BY day_of_week
ORDER BY total_bookings DESC;